// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACITU9VYYM0tlUUVZYdQCOqWKJgT_KouU',
    appId: '1:445748384517:web:3382615b6c6766c80b1d6c',
    messagingSenderId: '445748384517',
    projectId: 'coop-41b51',
    authDomain: 'coop-41b51.firebaseapp.com',
    storageBucket: 'coop-41b51.firebasestorage.app',
    measurementId: 'G-L7B135RSWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwooOGtA1yRTya_EOe-Oarb7Sin9gIlE',
    appId: '1:445748384517:android:9bcad9952963b5460b1d6c',
    messagingSenderId: '445748384517',
    projectId: 'coop-41b51',
    storageBucket: 'coop-41b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiLPg75lPR4sVD1znGiE8wKIpHbAVghx0',
    appId: '1:445748384517:ios:de0bbedf1667daad0b1d6c',
    messagingSenderId: '445748384517',
    projectId: 'coop-41b51',
    storageBucket: 'coop-41b51.firebasestorage.app',
    iosBundleId: 'com.example.coop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiLPg75lPR4sVD1znGiE8wKIpHbAVghx0',
    appId: '1:445748384517:ios:de0bbedf1667daad0b1d6c',
    messagingSenderId: '445748384517',
    projectId: 'coop-41b51',
    storageBucket: 'coop-41b51.firebasestorage.app',
    iosBundleId: 'com.example.coop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACITU9VYYM0tlUUVZYdQCOqWKJgT_KouU',
    appId: '1:445748384517:web:0da525baec09d8bd0b1d6c',
    messagingSenderId: '445748384517',
    projectId: 'coop-41b51',
    authDomain: 'coop-41b51.firebaseapp.com',
    storageBucket: 'coop-41b51.firebasestorage.app',
    measurementId: 'G-S28KWP7L5Q',
  );
}
